/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-08-09 13:56:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class eventCatalog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/include.jsp", Long.valueOf(1344516823976L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Welcome to Festival Event Registration System</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<link rel=\"StyleSheet\" href=\"css/struts2.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function previousPage()\r\n");
      out.write("{\r\n");
      out.write("\thistory.go(-1);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br/><br/><br/>\r\n");
      out.write("\t<table width=\"80%\" align=\"center\" border=\"2\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<div id=\"header\">&nbsp;\r\n");
      out.write("\t\t\t<div align=\"center\">Festival\r\n");
      out.write("\t\t\tRegistration System</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<table align=\"right\" cellpadding=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"menu\" align=\"center\"><a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\tLogout </a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"160\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"menu\" ><a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\tMy_Portal </a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"menu\" align=\"center\"><a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\tAbout</a><br />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"900\">\r\n");
      out.write("\t\t\t\t\t<div align=\"center\"><img src=\"images/greenhorizontalline.jpg\"\r\n");
      out.write("\t\t\t\t\t\theight=\"5\" width=\"100%\" /></div>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<div id=\"content\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<h3>Up-coming Events</h3>\r\n");
      out.write("\t\t\t\t\t<table width=\"96%\" border=\"1\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<tr bgcolor=\"#669966\">\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">Event Id</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">Event name</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">Description</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">Places</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">Duration</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">Event type</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">Maximum Seats</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">Available Seats</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_jstlcore_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr></tr>\r\n");
      out.write("\t\t\t\t<tr><td><br/></td></tr>\r\n");
      out.write("\t\t\t\t<tr><td><br/></td></tr>\r\n");
      out.write("\t\t\t\t<tr><td><br/></td></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jstlcore_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f0.setParent(null);
    // /eventCatalog.jsp(36,46) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f0.setValue("/index.jsp");
    int _jspx_eval_jstlcore_005furl_005f0 = _jspx_th_jstlcore_005furl_005f0.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f1.setParent(null);
    // /eventCatalog.jsp(40,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f1.setValue("/searchVisitor.htm");
    int _jspx_eval_jstlcore_005furl_005f1 = _jspx_th_jstlcore_005furl_005f1.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f2.setParent(null);
    // /eventCatalog.jsp(44,46) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f2.setValue("/about.jsp");
    int _jspx_eval_jstlcore_005furl_005f2 = _jspx_th_jstlcore_005furl_005f2.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_jstlcore_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_jstlcore_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fforEach_005f0.setParent(null);
    // /eventCatalog.jsp(70,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/eventCatalog.jsp(70,6) '${allEvents}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${allEvents}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /eventCatalog.jsp(70,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fforEach_005f0.setVar("event");
    int[] _jspx_push_body_count_jstlcore_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_jstlcore_005fforEach_005f0 = _jspx_th_jstlcore_005fforEach_005f0.doStartTag();
      if (_jspx_eval_jstlcore_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t<td>");
          if (_jspx_meth_jstlcore_005fout_005f0(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td>");
          if (_jspx_meth_jstlcore_005fout_005f1(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td>");
          if (_jspx_meth_jstlcore_005fout_005f2(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td>");
          if (_jspx_meth_jstlcore_005fout_005f3(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f4(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td>");
          if (_jspx_meth_jstlcore_005fout_005f5(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f6(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\t\r\n");
          out.write("\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f7(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_jstlcore_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_jstlcore_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_jstlcore_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_jstlcore_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_jstlcore_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_jstlcore_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /eventCatalog.jsp(72,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.eventid}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f0 = _jspx_th_jstlcore_005fout_005f0.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /eventCatalog.jsp(73,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f1 = _jspx_th_jstlcore_005fout_005f1.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /eventCatalog.jsp(74,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.description}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f2 = _jspx_th_jstlcore_005fout_005f2.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /eventCatalog.jsp(75,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.place}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f3 = _jspx_th_jstlcore_005fout_005f3.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /eventCatalog.jsp(76,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.duration}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f4 = _jspx_th_jstlcore_005fout_005f4.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /eventCatalog.jsp(77,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.eventtype}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f5 = _jspx_th_jstlcore_005fout_005f5.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f5);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f6.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /eventCatalog.jsp(78,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f6.setValue(new String("50"));
    int _jspx_eval_jstlcore_005fout_005f6 = _jspx_th_jstlcore_005fout_005f6.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f6);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f7.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /eventCatalog.jsp(79,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.seatsavailable}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f7 = _jspx_th_jstlcore_005fout_005f7.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f7);
    return false;
  }
}
