/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-08-09 13:49:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addEvent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/include.jsp", Long.valueOf(1344516825349L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Welcome to Festival Registration System</title>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("var nHist = window.history.length;\r\n");
      out.write("if(window.history[nHist] != window.location)\r\n");
      out.write("  window.history.forward();\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function isNumeric(value) {\r\n");
      out.write("\t  if (value==\"\" || value == null || !value.toString().match(/^[-]?\\d*\\.?\\d*$/))\r\n");
      out.write("\t  { return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  return true;\r\n");
      out.write("\t}\t\t\r\n");
      out.write("\tfunction echeck(str) {\r\n");
      out.write("\t\t   var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$/;   \r\n");
      out.write("\t\t\t   return emailPattern.test(str);   \t\t\t\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction validateForm()\r\n");
      out.write("\t{\r\n");
      out.write("\tvar eventName=document.forms[\"regform\"][\"eventName\"].value;\r\n");
      out.write("\tvar desc=document.forms[\"regform\"][\"desc\"].value;\r\n");
      out.write("\tvar place=document.forms[\"regform\"][\"place\"].value;\r\n");
      out.write("\tvar duration=document.forms[\"regform\"][\"duration\"].value;\t\r\n");
      out.write("\tvar eventType=document.forms[\"regform\"][\"eventType\"].value;\r\n");
      out.write("\tvar ticket=document.forms[\"regform\"][\"ticket\"].value;\t\r\n");
      out.write("\tif (eventName==null || eventName==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide event name\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\tif (desc==null || desc==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide event description\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\tif (place==null || place==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide place\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\tif (duration==null || duration==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide duration\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\tif (eventType==null || eventType==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide event type\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\tif (ticket==null || ticket==\"\" || ticket==0)\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide ticket\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\tif(isNumeric(ticket)==false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Invalid ticket\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\tfunction cancelRegistration()\r\n");
      out.write("\t{\r\n");
      out.write("\t\thistory.go(-1);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\" />\r\n");
      out.write("<link rel=\"StyleSheet\" href=\"css/struts2.css\" type=\"text/css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {\r\n");
      out.write("\tfont-size: 12\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write(".error {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\t\r\n");
      out.write("\t<br/><br/>\r\n");
      out.write("\t<form action=\"updateEvent.htm\" name=\"regform\" method=\"post\" onsubmit=\"return validateForm()\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"eventId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.eventid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\t\r\n");
      out.write("\t<input type=\"hidden\" name=\"sessionId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.sessionId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\t\r\n");
      out.write("\t<input type=\"hidden\" name=\"isAdd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.add}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t<table width=\"80%\" align=\"center\"  border=\"2\">\r\n");
      out.write("\t\t<tbody><tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<div id=\"header\">&nbsp;\r\n");
      out.write("\t\t\t<div align=\"center\">Festival Registration System</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tbody><tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<table align=\"right\" cellpadding=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<tbody><tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"menu\" align=\"center\"><a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\tEventCatalog_Page </a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody></table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"900\">\r\n");
      out.write("\t\t\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<table align=\"center\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tbody><tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>New Event Registration Page</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td align=\"center\" colspan=\"2\" style=\"font-style: italic;\">Fields marked (<span style=\"font-weight: bold;color: red; font-size: 15px;\">*</span>) are Mandatory</td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td></td><td></td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td></td><td></td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td><span style=\"font-weight: bold;color: red;font-size: 15px;\">*</span>\r\n");
      out.write("\t\t\t\t\t\t\tEvent Name:</td><td> \r\n");
      out.write("\t\t\t\t\t\t\t   <input type=\"text\" name=\"eventName\" size=\"25\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></input></td> \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t   <tr>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td><span style=\"font-weight: bold;color: red;font-size: 15px;\">*</span>\r\n");
      out.write("\t\t\t\t\t\t\tEvent Description: </td><td><input type=\"text\" name=\"desc\" size=\"25\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></input></td>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span style=\"font-weight: bold;color: red;font-size: 15px;\">*</span>\r\n");
      out.write("\t\t\t\t\t\t\tPlaces:</td><td><input type=\"text\" name=\"place\" size=\"25\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.place}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></input></td> \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t    <td><span style=\"font-weight: bold;color: red;font-size: 15px;\">*</span>\r\n");
      out.write("\t\t\t\t\t\t    Duration:</td><td><input type=\"text\" name=\"duration\" size=\"27\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.duration}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></input></td>\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t    <td><span style=\"font-weight: bold;color: red;font-size: 15px;\">*</span>\r\n");
      out.write("\t\t\t\t\t\t    Event Type:</td><td><input type=\"text\" name=\"eventType\" size=\"27\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.eventtype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></input></td>\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t\t\t   <td><span style=\"font-weight: bold;color: red;font-size: 15px;\">*</span>\r\n");
      out.write("\t\t\t\t\t\t    Available Tickets: </td><td> <input type=\"text\" name=\"ticket\" size=\"25\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.seatsavailable}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></input></td> \t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t   ");
      if (_jspx_meth_jstlcore_005fif_005f0(_jspx_page_context))
        return;
      out.write("\t\t\t\t\t  \t\t\t    \t \r\n");
      out.write("\t\t\t\t\t   <tr>\t\r\n");
      out.write("\t\t\t\t\t\t   <td colspan=\"2\" align=\"right\">\t\r\n");
      out.write("\t\t\t\t\t\t   ");
      if (_jspx_meth_jstlcore_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t     ");
      if (_jspx_meth_jstlcore_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody></table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<!-- content end -->\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr><td colspan=\"4\" align=\"center\"><div style=\"font-size: 15px; color: red; font-weight: bold;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${REGISTRATIONSTATUSMESSAGE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div></td></tr>\r\n");
      out.write("\t</tbody></table>\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jstlcore_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f0.setParent(null);
    // /addEvent.jsp(112,46) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f0.setValue("/catalog.htm");
    int _jspx_eval_jstlcore_005furl_005f0 = _jspx_th_jstlcore_005furl_005f0.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_jstlcore_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_jstlcore_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fif_005f0.setParent(null);
    // /addEvent.jsp(159,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.add == true}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_jstlcore_005fif_005f0 = _jspx_th_jstlcore_005fif_005f0.doStartTag();
    if (_jspx_eval_jstlcore_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\t\t\t\t\t   \r\n");
        out.write("\t\t\t\t\t   <tr>\r\n");
        out.write("                           <td><span style=\"font-weight: bold;color: red;font-size: 15px;\">*</span>Event Coordinator:</td>\r\n");
        out.write("                            <td>\r\n");
        out.write("                            <Select name=\"coordinator\" id=\"coordinator\">  \r\n");
        out.write("                            \t");
        if (_jspx_meth_jstlcore_005fforEach_005f0(_jspx_th_jstlcore_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                            </Select>\r\n");
        out.write("                            </td>                           \r\n");
        out.write("\t\t\t\t\t   </tr>\r\n");
        out.write("\t\t\t\t\t   <tr>\r\n");
        out.write("                           <td><span style=\"font-weight: bold;color: red;font-size: 15px;\">*</span>Number of Event Sessions:</td>\r\n");
        out.write("                            <td>\r\n");
        out.write("                            <Select name=\"eventSession\" id=\"eventSession\">                              \t\r\n");
        out.write("                            \t\t<option value=\"1\">");
        if (_jspx_meth_jstlcore_005fout_005f1(_jspx_th_jstlcore_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</option>   \r\n");
        out.write("                            \t\t<option value=\"2\">");
        if (_jspx_meth_jstlcore_005fout_005f2(_jspx_th_jstlcore_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</option> \r\n");
        out.write("                            \t\t<option value=\"3\">");
        if (_jspx_meth_jstlcore_005fout_005f3(_jspx_th_jstlcore_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</option> \r\n");
        out.write("                            \t\t<option value=\"4\">");
        if (_jspx_meth_jstlcore_005fout_005f4(_jspx_th_jstlcore_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</option> \r\n");
        out.write("                            \t\t<option value=\"5\">");
        if (_jspx_meth_jstlcore_005fout_005f5(_jspx_th_jstlcore_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</option> \t\t\r\n");
        out.write("                            </Select>\r\n");
        out.write("                            </td>                           \r\n");
        out.write("\t\t\t\t\t   </tr>\t\r\n");
        out.write("\t\t\t\t\t  ");
        int evalDoAfterBody = _jspx_th_jstlcore_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_jstlcore_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest.reuse(_jspx_th_jstlcore_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest.reuse(_jspx_th_jstlcore_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_jstlcore_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_jstlcore_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fif_005f0);
    // /addEvent.jsp(164,29) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/addEvent.jsp(164,29) '${eventCoordinator}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${eventCoordinator}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /addEvent.jsp(164,29) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fforEach_005f0.setVar("eventCoordinator");
    int[] _jspx_push_body_count_jstlcore_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_jstlcore_005fforEach_005f0 = _jspx_th_jstlcore_005fforEach_005f0.doStartTag();
      if (_jspx_eval_jstlcore_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            \t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventCoordinator.eventcoordinatorid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          if (_jspx_meth_jstlcore_005fout_005f0(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</option>                           \t\t\r\n");
          out.write("                            \t");
          int evalDoAfterBody = _jspx_th_jstlcore_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_jstlcore_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_jstlcore_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_jstlcore_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_jstlcore_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_jstlcore_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /addEvent.jsp(165,85) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventCoordinator.userName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f0 = _jspx_th_jstlcore_005fout_005f0.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fif_005f0);
    // /addEvent.jsp(174,48) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f1.setValue(new String("1"));
    int _jspx_eval_jstlcore_005fout_005f1 = _jspx_th_jstlcore_005fout_005f1.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fif_005f0);
    // /addEvent.jsp(175,48) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f2.setValue(new String("2"));
    int _jspx_eval_jstlcore_005fout_005f2 = _jspx_th_jstlcore_005fout_005f2.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fif_005f0);
    // /addEvent.jsp(176,48) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f3.setValue(new String("3"));
    int _jspx_eval_jstlcore_005fout_005f3 = _jspx_th_jstlcore_005fout_005f3.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fif_005f0);
    // /addEvent.jsp(177,48) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f4.setValue(new String("4"));
    int _jspx_eval_jstlcore_005fout_005f4 = _jspx_th_jstlcore_005fout_005f4.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fif_005f0);
    // /addEvent.jsp(178,48) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f5.setValue(new String("5"));
    int _jspx_eval_jstlcore_005fout_005f5 = _jspx_th_jstlcore_005fout_005f5.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f5);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_jstlcore_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_jstlcore_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fif_005f1.setParent(null);
    // /addEvent.jsp(185,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.add == true}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_jstlcore_005fif_005f1 = _jspx_th_jstlcore_005fif_005f1.doStartTag();
    if (_jspx_eval_jstlcore_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t   \t <input value=\"Add New Event\" type=\"submit\">\r\n");
        out.write("\t\t\t\t\t\t    ");
        int evalDoAfterBody = _jspx_th_jstlcore_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_jstlcore_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest.reuse(_jspx_th_jstlcore_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest.reuse(_jspx_th_jstlcore_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_jstlcore_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_jstlcore_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fif_005f2.setParent(null);
    // /addEvent.jsp(188,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event.add == false}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_jstlcore_005fif_005f2 = _jspx_th_jstlcore_005fif_005f2.doStartTag();
    if (_jspx_eval_jstlcore_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\t\t\t\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t   \t <input value=\"Update Event\" type=\"submit\">\r\n");
        out.write("\t\t\t\t\t\t    ");
        int evalDoAfterBody = _jspx_th_jstlcore_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_jstlcore_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest.reuse(_jspx_th_jstlcore_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fif_0026_005ftest.reuse(_jspx_th_jstlcore_005fif_005f2);
    return false;
  }
}
