/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-08-09 13:43:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.accenture.adf.businesstier.entity.Visitor;

public final class updatevisitor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/include.jsp", Long.valueOf(1344516825349L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Welcome to Festival Event Registration System</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<link rel=\"StyleSheet\" href=\"css/struts2.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function isNumeric(value) {\r\n");
      out.write("\t  if (value == null || !value.toString().match(/^[-]?\\d*\\.?\\d*$/))\r\n");
      out.write("\t  { return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  return true;\r\n");
      out.write("\t}\r\n");
      out.write("function echeck(str) {\r\n");
      out.write("\t   var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$/;   \r\n");
      out.write("\t\t   return emailPattern.test(str);   \t\t\t\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction validateForm()\r\n");
      out.write("\t{\r\n");
      out.write("\tvar fname=document.forms[\"updateVisitor\"][\"firstname\"].value;\r\n");
      out.write("\tvar lname=document.forms[\"updateVisitor\"][\"lastname\"].value;\r\n");
      out.write("\tvar email=document.forms[\"updateVisitor\"][\"email\"].value;\r\n");
      out.write("\t//var pwd=document.forms[\"updateVisitor\"][\"password\"].value;\r\n");
      out.write("\tvar phoneno=document.forms[\"updateVisitor\"][\"phoneno\"].value;\r\n");
      out.write("\tvar address=document.forms[\"updateVisitor\"][\"address\"].value;\r\n");
      out.write("\t//var cpwd=document.forms[\"updateVisitor\"][\"cpassword\"].value;\r\n");
      out.write("\t\r\n");
      out.write("\tif (fname==null || fname==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide Firstname\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\tif (lname==null || lname==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide Lastname\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\tif (email==null || email==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide email\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t/* if (pwd==null || pwd==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide password\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\tif(pwd!=cpwd)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Password and confirm password must be same !!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t} */\r\n");
      out.write("\tif (echeck(email)==false){\r\n");
      out.write("\t\talert(\"Invalid EmailID\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (phoneno==null || phoneno==\"\")\r\n");
      out.write("\t  {\r\n");
      out.write("\t  alert(\"Please provide phoneno\");\r\n");
      out.write("\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\tif(isNumeric(phoneno)==false)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Invalid Phonenumber\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\tfunction cancelUpdate()\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"Your request to update info has been cancelled\");\r\n");
      out.write("\t\t//window.location.replace(\"visitormain.jsp\");\r\n");
      out.write("\t\tdocument.forms[0].action = \"searchVisitor.htm\";\r\n");
      out.write("\t\tdocument.forms[0].submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction displayStatus()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar updstatus=document.forms[\"updateVisitor\"][\"status\"].value;\r\n");
      out.write("\t\tif(updstatus==\"success\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Visitor details succesfully updated.. Please Login again..\");\r\n");
      out.write("\t\t\twindow.location.replace(\"index.jsp\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".error {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"displayStatus()\">\r\n");
      out.write("\t\r\n");
      out.write("\t");

	String uname=request.getParameter("vname");
	String fname=request.getParameter("fname");
	String lname=request.getParameter("lname");
	String email=request.getParameter("email");
	String phoneno=request.getParameter("phoneno");
	String address=request.getParameter("address");
	
      out.write("\r\n");
      out.write("\t<form method=\"post\" name=\"updateVisitor\" action=\"updatevisitor.htm\" onsubmit=\"return validateForm()\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"status\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<table width=\"80%\" height=\"100%\" border=\"1\" align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<div id=\"header\">&nbsp;\r\n");
      out.write("\t\t\t<div align=\"center\"><a\r\n");
      out.write("\t\t\t\thref=\"");
      if (_jspx_meth_jstlcore_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"> Festival Registration System</a></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<table align=\"right\" cellpadding=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"menu\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"> Logout </a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"menu\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"> About</a><br />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"900\">\r\n");
      out.write("\t\t\t\t\t<div id=\"style1\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<h3>Update your information</h3>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<table align=\"center\" border=\"0\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr><td align=\"center\" colspan=\"2\" style=\"font-style: italic;\">Fields marked (<span style=\"font-weight: bold;color: red; font-size: 15px;\">*</span>) are Mandatory</td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td></td><td></td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td></td><td></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>First Name:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
      out.print( fname );
      out.write("\" name=\"firstname\" size=\"25\" ></input></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Last Name:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
      out.print( lname );
      out.write("\" name=\"lastname\" size=\"25\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>User Name:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
      out.print( uname );
      out.write("\" disabled=\"disabled\" size=\"25\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print( uname );
      out.write("\" name=\"username\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><span style=\"font-weight: bold;color: red;font-size: 15px;\">*</span>Password:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" size=\"27\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><span style=\"font-weight: bold;color: red;font-size: 15px;\">*</span>Confirm Password:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"password\" name=\"cpassword\" size=\"27\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Email:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
      out.print( email );
      out.write("\" name=\"email\" size=\"25\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Phone Number:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" value=\"");
      out.print( phoneno );
      out.write("\" name=\"phoneno\" size=\"25\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Address:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"address\" value=\"");
      out.print( address );
      out.write("\" size=\"25\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" align=\"right\"><input value=\"Cancel\" type=\"Button\" onclick=\"cancelUpdate()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input value=\"Update\" type=\"submit\" ></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<!-- content end -->\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" align=\"center\" style=\"error\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${updatestatus}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jstlcore_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f0.setParent(null);
    // /updatevisitor.jsp(120,10) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f0.setValue("/searchVisitor.htm");
    int _jspx_eval_jstlcore_005furl_005f0 = _jspx_th_jstlcore_005furl_005f0.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f1.setParent(null);
    // /updatevisitor.jsp(130,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f1.setValue("/index.jsp");
    int _jspx_eval_jstlcore_005furl_005f1 = _jspx_th_jstlcore_005furl_005f1.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f2.setParent(null);
    // /updatevisitor.jsp(135,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f2.setValue("/about.jsp");
    int _jspx_eval_jstlcore_005furl_005f2 = _jspx_th_jstlcore_005furl_005f2.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f2);
    return false;
  }
}
