/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-08-09 13:40:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class visitormain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/include.jsp", Long.valueOf(1344516825349L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fjstlcore_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjstlcore_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjstlcore_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fjstlcore_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fjstlcore_005fchoose.release();
    _005fjspx_005ftagPool_005fjstlcore_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fjstlcore_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Welcome to Festival Event Registration System</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<link rel=\"StyleSheet\" href=\"css/struts2.css\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validateForm()\r\n");
      out.write("{\r\n");
      out.write("var ename=document.forms[\"logForm\"][\"eventname\"].value;\r\n");
      out.write("if (ename==null || ename==\"\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"Please provide Eventname to Search..\");\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form name=\"logForm\" method=\"post\" action=\"searchEventByName.htm\">\r\n");
      out.write("\t<table width=\"80%\" align=\"center\" border=\"2\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<div id=\"header\">&nbsp;\r\n");
      out.write("\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\tFestival Registration System</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<table align=\"right\" cellpadding=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"menu\" align=\"center\"><a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\tLogout </a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"160\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"menu\" align=\"center\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      if (_jspx_meth_jstlcore_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"> Change_Password </a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"160\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"menu\" align=\"center\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      if (_jspx_meth_jstlcore_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"> Event_Catalog </a></div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"90\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"menu\" align=\"center\"><a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f3(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\tAbout</a><br /></div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"1000\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"5\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div align=\"center\" id=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Festival Portal Page: Welcome <span style=\"background-color: yellow;\">");
      if (_jspx_meth_jstlcore_005fout_005f0(_jspx_page_context))
        return;
      out.write("</span> to your portal page.....</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<table cellpadding=\"4\" border=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width=\"1000\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"coursesbody\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><strong>Your personal\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinformation</strong> is below. To change your information, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">click here </a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"style1\">Username :");
      if (_jspx_meth_jstlcore_005fout_005f1(_jspx_page_context))
        return;
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t \t<p class=\"style1\">Visitor ID: ");
      if (_jspx_meth_jstlcore_005fout_005f2(_jspx_page_context))
        return;
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"style1\">Email: ");
      if (_jspx_meth_jstlcore_005fout_005f3(_jspx_page_context))
        return;
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"style1\">Phone Number: ");
      if (_jspx_meth_jstlcore_005fout_005f4(_jspx_page_context))
        return;
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"style1\">Address: ");
      if (_jspx_meth_jstlcore_005fout_005f5(_jspx_page_context))
        return;
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<div align=\"center\"><img src=\"images/greenhorizontalline.jpg\"\r\n");
      out.write("\t\t\t\theight=\"5\" width=\"100%\" /></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"content\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"content\"><strong>To release a ticket you have for an up-coming attraction, please find the attraction below, and click the Release link.</strong></p>\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"96%\" border=\"1\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr bgcolor=\"#66CC99\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">Confirmation #</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">Event ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">Event Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">Description</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">Places</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">Duration</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">Event Type</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">Event Session</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">Event Coordinator</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">Action</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("                                ");
      if (_jspx_meth_jstlcore_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"10\" align=\"center\" style=\"font-weight: bold; color: red;\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RegError}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div align=\"center\"><img src=\"images/greenhorizontalline.jpg\"\r\n");
      out.write("\t\t\t\theight=\"5\" width=\"100%\" /></div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div id=\"content\" align=\"center\">\r\n");
      out.write("\t\t\t<p class=\"content\"><strong>To get a ticket for an up-coming attraction, please find the attraction below, and click the Register link.</strong></p>\r\n");
      out.write("\t\t\t<p class=\"content\">Enter eventname to search <input type=\"text\" name=\"eventname\"></input>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Search\"></input>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<table class=\"content\" width=\"96%\" border=\"1\" align=\"center\">\r\n");
      out.write("\t\t\t\t<tr bgcolor=\"#66CC99\">\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Event id</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Event name<br/>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"><img src=\"images/upointer.jpg\"/></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      if (_jspx_meth_jstlcore_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"><img src=\"images/dpointer.jpg\"/></a>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Description</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Places</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Duration</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Event type</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Event Session</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Available Tickets</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_jstlcore_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_jstlcore_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f0.setParent(null);
    // /visitormain.jsp(41,46) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f0.setValue("/index.jsp");
    int _jspx_eval_jstlcore_005furl_005f0 = _jspx_th_jstlcore_005furl_005f0.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f1.setParent(null);
    // /visitormain.jsp(46,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f1.setValue("/changePWD.jsp");
    int _jspx_eval_jstlcore_005furl_005f1 = _jspx_th_jstlcore_005furl_005f1.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f2.setParent(null);
    // /visitormain.jsp(50,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f2.setValue("/catalog.htm");
    int _jspx_eval_jstlcore_005furl_005f2 = _jspx_th_jstlcore_005furl_005f2.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f3.setParent(null);
    // /visitormain.jsp(53,46) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f3.setValue("/about.jsp");
    int _jspx_eval_jstlcore_005furl_005f3 = _jspx_th_jstlcore_005furl_005f3.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f0.setParent(null);
    // /visitormain.jsp(66,81) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${visitor.firstName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f0 = _jspx_th_jstlcore_005fout_005f0.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f4.setParent(null);
    // /visitormain.jsp(74,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f4.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/updatevisitor.jsp?vname=${visitor.userName}&fname=${visitor.firstName}&lname=${visitor.lastName}&email=${visitor.email}&phoneno=${visitor.phoneNumber}&address=${visitor.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005furl_005f4 = _jspx_th_jstlcore_005furl_005f4.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f1.setParent(null);
    // /visitormain.jsp(75,37) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${visitor.userName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f1 = _jspx_th_jstlcore_005fout_005f1.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f2.setParent(null);
    // /visitormain.jsp(76,40) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${visitor.visitorId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f2 = _jspx_th_jstlcore_005fout_005f2.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f3.setParent(null);
    // /visitormain.jsp(77,34) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${visitor.email}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f3 = _jspx_th_jstlcore_005fout_005f3.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f4.setParent(null);
    // /visitormain.jsp(78,41) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${visitor.phoneNumber}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f4 = _jspx_th_jstlcore_005fout_005f4.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f5.setParent(null);
    // /visitormain.jsp(79,36) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${visitor.address}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f5 = _jspx_th_jstlcore_005fout_005f5.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f5);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_jstlcore_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_jstlcore_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fforEach_005f0.setParent(null);
    // /visitormain.jsp(102,32) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/visitormain.jsp(102,32) '${regEvents}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${regEvents}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /visitormain.jsp(102,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fforEach_005f0.setVar("regEvent");
    int[] _jspx_push_body_count_jstlcore_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_jstlcore_005fforEach_005f0 = _jspx_th_jstlcore_005fforEach_005f0.doStartTag();
      if (_jspx_eval_jstlcore_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tr align=\"center\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td>");
          if (_jspx_meth_jstlcore_005fout_005f6(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f7(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f8(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f9(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f10(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f11(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f12(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f13(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f14(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"100px\" bgcolor=\"#CCCC99\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"");
          if (_jspx_meth_jstlcore_005furl_005f5(_jspx_th_jstlcore_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f0))
            return true;
          out.write("\">Release</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_jstlcore_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_jstlcore_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_jstlcore_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_jstlcore_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_jstlcore_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_jstlcore_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f6.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /visitormain.jsp(104,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(visitor.lastName,0,4)}${fn:substring(visitor.firstName,0,3)}-${regEvent[8]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0, false));
    int _jspx_eval_jstlcore_005fout_005f6 = _jspx_th_jstlcore_005fout_005f6.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f6);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f7.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /visitormain.jsp(105,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regEvent[0]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f7 = _jspx_th_jstlcore_005fout_005f7.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f7);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f8.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /visitormain.jsp(106,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regEvent[1]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f8 = _jspx_th_jstlcore_005fout_005f8.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f8);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f9 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f9.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /visitormain.jsp(107,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f9.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regEvent[2]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f9 = _jspx_th_jstlcore_005fout_005f9.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f9);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f10 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f10.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /visitormain.jsp(108,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f10.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regEvent[5]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f10 = _jspx_th_jstlcore_005fout_005f10.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f10);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f11 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f11.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /visitormain.jsp(109,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f11.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regEvent[3]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f11 = _jspx_th_jstlcore_005fout_005f11.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f11);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f12 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f12.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /visitormain.jsp(110,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f12.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regEvent[4]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f12 = _jspx_th_jstlcore_005fout_005f12.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f12);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f13(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f13 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f13.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f13.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /visitormain.jsp(111,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f13.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regEvent[7]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f13 = _jspx_th_jstlcore_005fout_005f13.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f13);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f14(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f14 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f14.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f14.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /visitormain.jsp(112,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f14.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${regEvent[6]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f14 = _jspx_th_jstlcore_005fout_005f14.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f14);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f14);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f0);
    // /visitormain.jsp(114,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f5.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/eventunreg.htm?eventId=${regEvent[0]}&eventsessionid=${regEvent[7]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005furl_005f5 = _jspx_th_jstlcore_005furl_005f5.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f6.setParent(null);
    // /visitormain.jsp(148,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f6.setValue("/displayasc.htm");
    int _jspx_eval_jstlcore_005furl_005f6 = _jspx_th_jstlcore_005furl_005f6.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f6);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f7.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f7.setParent(null);
    // /visitormain.jsp(149,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f7.setValue("/displaydesc.htm");
    int _jspx_eval_jstlcore_005furl_005f7 = _jspx_th_jstlcore_005furl_005f7.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f7);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_jstlcore_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_jstlcore_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fforEach_005f1.setParent(null);
    // /visitormain.jsp(158,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/visitormain.jsp(158,4) '${allEvents}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${allEvents}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /visitormain.jsp(158,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fforEach_005f1.setVar("event");
    int[] _jspx_push_body_count_jstlcore_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_jstlcore_005fforEach_005f1 = _jspx_th_jstlcore_005fforEach_005f1.doStartTag();
      if (_jspx_eval_jstlcore_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f15(_jspx_th_jstlcore_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f16(_jspx_th_jstlcore_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f17(_jspx_th_jstlcore_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f18(_jspx_th_jstlcore_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f19(_jspx_th_jstlcore_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f20(_jspx_th_jstlcore_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td align=\"center\">");
          if (_jspx_meth_jstlcore_005fout_005f21(_jspx_th_jstlcore_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
            return true;
          out.write("</td>\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_jstlcore_005fchoose_005f0(_jspx_th_jstlcore_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_jstlcore_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_jstlcore_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_jstlcore_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_jstlcore_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_jstlcore_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fjstlcore_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_jstlcore_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f15(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f15 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f15.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f15.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f1);
    // /visitormain.jsp(160,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f15.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event[0]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f15 = _jspx_th_jstlcore_005fout_005f15.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f15);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f15);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f16(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f16 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f16.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f16.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f1);
    // /visitormain.jsp(161,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f16.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event[1]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f16 = _jspx_th_jstlcore_005fout_005f16.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f16);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f16);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f17(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f17 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f17.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f17.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f1);
    // /visitormain.jsp(162,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f17.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event[2]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f17 = _jspx_th_jstlcore_005fout_005f17.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f17);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f17);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f18(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f18 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f18.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f18.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f1);
    // /visitormain.jsp(163,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f18.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event[5]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f18 = _jspx_th_jstlcore_005fout_005f18.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f18);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f18);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f19(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f19 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f19.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f19.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f1);
    // /visitormain.jsp(164,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f19.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event[3]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f19 = _jspx_th_jstlcore_005fout_005f19.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f19);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f19);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f20(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f20 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f20.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f20.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f1);
    // /visitormain.jsp(165,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f20.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event[4]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f20 = _jspx_th_jstlcore_005fout_005f20.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f20);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f20);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f21(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f21 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f21.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f21.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f1);
    // /visitormain.jsp(166,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f21.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event[7]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f21 = _jspx_th_jstlcore_005fout_005f21.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f21.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f21);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f21);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_jstlcore_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fjstlcore_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_jstlcore_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fforEach_005f1);
    int _jspx_eval_jstlcore_005fchoose_005f0 = _jspx_th_jstlcore_005fchoose_005f0.doStartTag();
    if (_jspx_eval_jstlcore_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t  ");
        if (_jspx_meth_jstlcore_005fwhen_005f0(_jspx_th_jstlcore_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
          return true;
        out.write("\t\t\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_jstlcore_005fotherwise_005f0(_jspx_th_jstlcore_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
          return true;
        out.write("\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_jstlcore_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_jstlcore_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fchoose.reuse(_jspx_th_jstlcore_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fchoose.reuse(_jspx_th_jstlcore_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_jstlcore_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fjstlcore_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_jstlcore_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fchoose_005f0);
    // /visitormain.jsp(168,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event[6] != 0}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_jstlcore_005fwhen_005f0 = _jspx_th_jstlcore_005fwhen_005f0.doStartTag();
    if (_jspx_eval_jstlcore_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<td width=\"100px\" bgcolor=\"#CCCC99\" align=\"center\">\r\n");
        out.write("\t\t\t\t\t\t\t");
        if (_jspx_meth_jstlcore_005fout_005f22(_jspx_th_jstlcore_005fwhen_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<strong> seats left.</strong>\r\n");
        out.write("\t\t\t\t\t\t \t    <a href=\"");
        if (_jspx_meth_jstlcore_005furl_005f8(_jspx_th_jstlcore_005fwhen_005f0, _jspx_page_context, _jspx_push_body_count_jstlcore_005fforEach_005f1))
          return true;
        out.write("\">Register</a>\t\t\t\t\t\t \t \r\n");
        out.write("\t\t\t\t\t\t\t</td>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_jstlcore_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_jstlcore_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fwhen_0026_005ftest.reuse(_jspx_th_jstlcore_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fwhen_0026_005ftest.reuse(_jspx_th_jstlcore_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fout_005f22(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_jstlcore_005fout_005f22 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_jstlcore_005fout_005f22.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fout_005f22.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fwhen_005f0);
    // /visitormain.jsp(170,7) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005fout_005f22.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${event[6]}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005fout_005f22 = _jspx_th_jstlcore_005fout_005f22.doStartTag();
    if (_jspx_th_jstlcore_005fout_005f22.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f22);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005fout_005f22);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005furl_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_jstlcore_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_jstlcore_005furl_005f8.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005furl_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fwhen_005f0);
    // /visitormain.jsp(172,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_jstlcore_005furl_005f8.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/eventreg.htm?eventId=${event[0]}&sessionId=${event[7]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_jstlcore_005furl_005f8 = _jspx_th_jstlcore_005furl_005f8.doStartTag();
    if (_jspx_th_jstlcore_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_jstlcore_005furl_005f8);
    return false;
  }

  private boolean _jspx_meth_jstlcore_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_jstlcore_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_jstlcore_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  jstlcore:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_jstlcore_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fjstlcore_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_jstlcore_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_jstlcore_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_jstlcore_005fchoose_005f0);
    int _jspx_eval_jstlcore_005fotherwise_005f0 = _jspx_th_jstlcore_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_jstlcore_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<td width=\"100px\" bgcolor=\"#CCCC99\" align=\"center\"><strong>No\r\n");
        out.write("\t\t\t\t\t\t\tseats left</strong></td>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_jstlcore_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_jstlcore_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fjstlcore_005fotherwise.reuse(_jspx_th_jstlcore_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fjstlcore_005fotherwise.reuse(_jspx_th_jstlcore_005fotherwise_005f0);
    return false;
  }
}
